const data = [
	{
		id: 1,
		name: "Agra",
		info: "Agra is a city in northern India, known for the iconic Taj Mahal, a stunning white marble mausoleum built by Mughal emperor Shah Jahan in memory of his beloved wife. Agra is also home to several other historic and architectural wonders, including Agra Fort and Fatehpur Sikri.",
		image: "https://cdn.thecodehelp.in/Agra.jpeg",
		price: "35,758",
	},
	{
		id: 2,
		name: "Jaipur",
		info: `Jaipur is the capital city of the Indian state of Rajasthan, known for its stunning pink-hued buildings and palaces. The city is also known as the "Pink City" due to the color of many of its buildings. Jaipur is famous for its intricate textiles, colorful handicrafts, and delicious cuisine.`,
		image: "https://cdn.thecodehelp.in/Jaipur.jpeg",
		price: "82,560",
	},
	{
		id: 3,
		name: "Goa",
		info: " Goa is a small state on India's western coast, known for its stunning beaches, vibrant nightlife, and Portuguese-influenced architecture. The state is also known for its spicy seafood dishes and unique cultural traditions.",
		image: "https://cdn.thecodehelp.in/Goa.jpeg",
		price: "29,695",
	},
	{
		id: 4,
		name: "Varanasi",
		info: "Varanasi is a holy city in northern India, situated on the banks of the sacred river Ganges. The city is a major pilgrimage site for Hindus and is famous for its ancient temples, winding alleyways, and colorful festivals.",
		image: "https://cdn.thecodehelp.in/Varanasi.jpeg",
		price: "31,095",
	},
	{
		id: 5,
		name: "Darjeeling",
		info: "Starting in the colorful port city of Gdańsk, you'll escape the crowds and embrace the understated elegance of ready-for-prime-time Poland for 10 days. With an expert Rick Steves guide at your side, you'll experience mighty Malbork castle, the cobbly-cute village of Toruń, Poland's contemporary capital of Warsaw, the spiritual Jasna Góra Monastery, and charming Kraków — Poland's finest city. In this land of surprises — so trendy and hip, yet steeped in history — there's so much to discover. Join us for the Best of Poland in 10 Days!",
		image: "https://cdn.thecodehelp.in/Darjeeling.jpeg",
		price: "78,595",
	},
	{
		id: 6,
		name: "Jaisalmer",
		info: "Jaisalmer is a city in the Indian state of Rajasthan, known for its stunning sandstone architecture and its location in the heart of the Thar Desert. The city is home to several impressive palaces and fortresses, as well as unique cultural traditions and handicrafts.",
		image: "https://cdn.thecodehelp.in/Jaisalmer.jpeg",
		price: "68,595",
	},
	{
		id: 7,
		name: "Kochi",
		info: "Kochi is a port city in the Indian state of Kerala, known for its historic connections to trade and commerce. The city is home to several stunning churches, synagogues, and mosques, as well as a rich culinary tradition that blends Indian, Portuguese, and other influences.",
		image: "https://cdn.thecodehelp.in/Kochi.jpeg",
		price: "68,595",
	},
	{
		id: 8,
		name: "Manali",
		info: "Manali is a picturesque hill station in the Indian state of Himachal Pradesh, known for its stunning landscapes, adventure sports, and tranquil ambiance. It's a popular destination for both honeymooners and adventure seekers.",
		image: "https://imgs.search.brave.com/nHOocVSm1hS0J2V8IX_owqCg6W47MwB0uyT5trsPUck/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93YWxs/cGFwZXJjYXZlLmNv/bS93cC93cDQ1Mjg3/MDcuanBn",
		price: "54,890",
	},
	{
		id: 9,
		name: "Shimla",
		info: "Shimla, the capital city of Himachal Pradesh, is renowned for its colonial architecture, scenic views, and cool climate. It's a favorite summer retreat and a popular destination for nature lovers.",
		image: "https://imgs.search.brave.com/SE--aTtOb9KTLnnkVnxCewYydfv0TqUf7Z9AYdSrRxY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/YXVkbGV5dHJhdmVs/LmNvbS83MDAvNTAw/Lzc5LzI2OTgyNi12/aWV3LW9mLXNoaW1s/YS5qcGc",
		price: "43,675",
	},
	{
		id: 10,
		name: "Ooty",
		info: "Ooty is a charming hill station in Tamil Nadu, known for its lush green landscapes, tea gardens, and pleasant climate. The Nilgiri Mountain Railway and the botanical gardens are major attractions here.",
		image: "https://imgs.search.brave.com/8QkilsUvDZIAkFMopbUiGzt8RPU29L2miqjGuw3mQGs/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzA0LzEwLzEzLzIy/LzM2MF9GXzQxMDEz/MjI5OV9GY2V4WE9G/MmRDMGo3M0NHcjRs/bTlqWTlvTmhORXBz/Sy5qcGc",
		price: "59,430",
	},
	{
		id: 11,
		name: "Rishikesh",
		info: "Rishikesh, located in the foothills of the Himalayas, is known as the 'Yoga Capital of the World.' It's also a hub for adventure activities like river rafting and trekking.",
		image: "https://imgs.search.brave.com/1SnkpWNn0Fc9DKs7L0c2_vVZXkqqBM2JCKUnhY1bfgc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YTEudGhyaWxsb3Bo/aWxpYS5jb20vZmls/ZXN0b3JlLzRtZnlx/ZmhnNXI4ODYwZ2Iz/N2k1MDZrZWVmNmZf/Uml2ZXItUmFmdGlu/Zy1pbi1SaXNoaWtl/c2guanBn",
		price: "39,150",
	},
	{
		id: 12,
		name: "Mysore",
		info: "Mysore is a historic city in Karnataka, famous for its grand palaces, vibrant cultural heritage, and the renowned Mysore Dasara festival. The city is also known for its sandalwood products.",
		image: "https://imgs.search.brave.com/z-9FKFZIjHoR19Qc6Lda06J_KfobqLYcwv9pkTcmhlw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMudHJhdmVsdHJp/YW5nbGUuY29tL2Js/b2cvd3AtY29udGVu/dC91cGxvYWRzLzIw/MTcvMTIvbXlzb3Jl/LXBhbGFjZTEuanBn",
		price: "49,330",
	},
	{
		id: 13,
		name: "Udaipur",
		info: "Udaipur, often referred to as the 'City of Lakes,' is a stunning city in Rajasthan known for its beautiful palaces, serene lakes, and rich history. The City Palace and Lake Pichola are must-visit attractions.",
		image: "https://imgs.search.brave.com/Aszn1j6OzqljA-uAmCA-7Vj2g8PJRgzVVD39adNB0_I/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9scC1j/bXMtcHJvZHVjdGlv/bi5pbWdpeC5uZXQv/MjAxOS0wNi9HZXR0/eUltYWdlcy0xNTQ5/NjgwMjBfaGlnaC5q/cGc_dz0xOTIwJmg9/NjQwJmZpdD1jcm9w/JmNyb3A9ZmFjZXMs/ZWRnZXMmYXV0bz1m/b3JtYXQmcT03NQ",
		price: "64,750",
	},
	{
		id: 14,
		name: "Leh-Ladakh",
		info: "Leh-Ladakh is a remote region in northern India, known for its breathtaking landscapes, Buddhist monasteries, and adventure activities. The stark beauty of the region is unmatched.",
		image: "https://imgs.search.brave.com/xwiegY1WKlzBs5OkzkALdGxUqvnyzEgqitB8NnlB83c/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTE4/NTM3MTY4Ny9waG90/by90aGUtcGVyc29u/LWxvb2stYXQtc3Vu/c2V0LWFuZC1sZWgt/Y2l0eS1pbi1sZWgt/bGFkYWtoLWluZGlh/LmpwZz9zPTYxMng2/MTImdz0wJms9MjAm/Yz1qUjVyNlkzUWpz/QU02TWgzNTBfMkJj/ZTVqemZjWmZQRUNO/QTdsTjgzSW9BPQ",
		price: "88,670",
	},
	{
		id: 15,
		name: "Andaman and Nicobar Islands",
		info: "The Andaman and Nicobar Islands are a tropical paradise in the Bay of Bengal, known for their pristine beaches, crystal-clear waters, and vibrant marine life. It's an ideal destination for water sports and relaxation.",
		image: "https://imgs.search.brave.com/t8q6ez7yuLO1ce9v1PbnFWT7YCvnRlDiaTX5NUqrzO4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/dG91cm15aW5kaWEu/Y29tL3N0YXRlcy9h/bmRhbWFuL2ltYWdl/cy9pc2xhbmRzLWlu/LWFuZGFtYW4xLmpw/Zw",
		price: "92,400",
	},
	{
		id: 16,
		name: "Kodaikanal",
		info: "Kodaikanal, known as the 'Princess of Hill Stations,' is a serene town in Tamil Nadu. It's famous for its mist-covered mountains, lush forests, and the beautiful Kodaikanal Lake.",
		image: "https://imgs.search.brave.com/dDpa22xYg031-eWyFFcIHFJplw5RZsDL-jXz08eIULU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMuY250cmF2ZWxs/ZXIuaW4vcGhvdG9z/LzY1NzJlMzE0OGI1/MDFmNGQ5NjdhNzY3/My8xOjEvd18zNTQs/Y19saW1pdC9sZWFk/LmpwZw",
		price: "57,290",
	},
	{
		id: 17,
		name: "Ranthambore",
		info: "Ranthambore National Park, located in Rajasthan, is one of the largest and most famous national parks in India. It's known for its population of Bengal tigers and diverse wildlife.",
		image: "https://imgs.search.brave.com/eF1lOcM5zmHZHxxffKsNr8pmBgSzXen3o3LyG9RfU4E/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9kYXRh/LmFnYXRldHJhdmVs/LmNvbS9pbWFnZXMv/cGhvdG9nYWxsZXJ5/LzIwMjAvcmFudGhh/bWJvcmUtZm9ydC5q/cGc",
		price: "72,130",
	},
];

export default data;
